Search.appendIndex(
    [
                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\EvaluationContextConverter",
            "name": "EvaluationContextConverter",
            "summary": "Converts\u0020an\u0020OpenFeature\u0020EvaluationContext\u0020into\u0020a\u0020LDContext.",
            "url": "classes/LaunchDarkly-OpenFeature-EvaluationContextConverter.html"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\EvaluationContextConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/LaunchDarkly-OpenFeature-EvaluationContextConverter.html#method___construct"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\EvaluationContextConverter\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Sets\u0020a\u0020logger\u0020instance\u0020on\u0020the\u0020object.",
            "url": "classes/LaunchDarkly-OpenFeature-EvaluationContextConverter.html#method_setLogger"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\EvaluationContextConverter\u003A\u003AtoLdContext\u0028\u0029",
            "name": "toLdContext",
            "summary": "Create\u0020an\u0020LDContext\u0020from\u0020an\u0020EvaluationContext.",
            "url": "classes/LaunchDarkly-OpenFeature-EvaluationContextConverter.html#method_toLdContext"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider",
            "name": "Provider",
            "summary": "An\u0020OpenFeatureProvider\u0020which\u0020enables\u0020the\u0020use\u0020of\u0020the\u0020LaunchDarkly\u0020Server\u002DSide\nSDK\u0020for\u0020PHP\u0020with\u0020OpenFeature.",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Instantiate\u0020a\u0020new\u0020instance\u0020of\u0020this\u0020provider,\u0020backed\u0020by\u0020the\u0020provided\u0020LDClient\u0020instance.",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method___construct"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_getMetadata"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Sets\u0020a\u0020logger\u0020instance\u0020on\u0020the\u0020object.",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_setLogger"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AgetHooks\u0028\u0029",
            "name": "getHooks",
            "summary": "",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_getHooks"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AresolveBooleanValue\u0028\u0029",
            "name": "resolveBooleanValue",
            "summary": "Resolves\u0020the\u0020flag\u0020value\u0020for\u0020the\u0020provided\u0020flag\u0020key\u0020as\u0020a\u0020boolean",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_resolveBooleanValue"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AresolveStringValue\u0028\u0029",
            "name": "resolveStringValue",
            "summary": "Resolves\u0020the\u0020flag\u0020value\u0020for\u0020the\u0020provided\u0020flag\u0020key\u0020as\u0020a\u0020string",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_resolveStringValue"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AresolveIntegerValue\u0028\u0029",
            "name": "resolveIntegerValue",
            "summary": "Resolves\u0020the\u0020flag\u0020value\u0020for\u0020the\u0020provided\u0020flag\u0020key\u0020as\u0020an\u0020integer",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_resolveIntegerValue"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AresolveFloatValue\u0028\u0029",
            "name": "resolveFloatValue",
            "summary": "Resolves\u0020the\u0020flag\u0020value\u0020for\u0020the\u0020provided\u0020flag\u0020key\u0020as\u0020a\u0020float",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_resolveFloatValue"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\Provider\u003A\u003AresolveObjectValue\u0028\u0029",
            "name": "resolveObjectValue",
            "summary": "Resolves\u0020the\u0020flag\u0020value\u0020for\u0020the\u0020provided\u0020flag\u0020key\u0020as\u0020an\u0020object",
            "url": "classes/LaunchDarkly-OpenFeature-Provider.html#method_resolveObjectValue"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\ProviderMetaData",
            "name": "ProviderMetaData",
            "summary": "Object\u0020responsible\u0020for\u0020returning\u0020metadata\u0020information\u0020associated\u0020with\u0020the\nconfigured\u0020provider.",
            "url": "classes/LaunchDarkly-OpenFeature-ProviderMetaData.html"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\ProviderMetaData\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Returns\u0020string\u0020identifier\u0020for\u0020this\u0020provider\u0020type.",
            "url": "classes/LaunchDarkly-OpenFeature-ProviderMetaData.html#method_getName"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\ResolutionDetailsConverter",
            "name": "ResolutionDetailsConverter",
            "summary": "Converts\u0020an\u0020EvaluationDetail\u0020into\u0020an\u0020OpenFeature\u0020ResolutionDetails.",
            "url": "classes/LaunchDarkly-OpenFeature-ResolutionDetailsConverter.html"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature\\ResolutionDetailsConverter\u003A\u003AtoResolutionDetails\u0028\u0029",
            "name": "toResolutionDetails",
            "summary": "",
            "url": "classes/LaunchDarkly-OpenFeature-ResolutionDetailsConverter.html#method_toResolutionDetails"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\LaunchDarkly\\OpenFeature",
            "name": "OpenFeature",
            "summary": "",
            "url": "namespaces/launchdarkly-openfeature.html"
        },                {
            "fqsen": "\\LaunchDarkly",
            "name": "LaunchDarkly",
            "summary": "",
            "url": "namespaces/launchdarkly.html"
        }            ]
);
