version: 2

publications:
  - url: https://packagist.org/packages/launchdarkly/openfeature-server
    description: Packagist

branches:
  - name: main

jobs:
  - docker:
      image: ldcircleci/php-sdk-release:4  # Releaser's default for PHP is still php-sdk-release:3, which is PHP 7.x
    template:
      name: php

documentation:
  gitHubPages: true
  title: "LaunchDarkly\\OpenFeature"

sdk:
  displayName: "PHP OpenFeature Provider Server-Side"
